# Site settings
title: The Vanual
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Testing testing testing
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalinks: none

# Build settings
markdown: kramdown
